### ISSUE TITLE
Follow README example for Milestone 3

### ISSUE THREAD

**Issue by derekrodgers** [UBC-MDS/vancouver-tree-height-geo-group-33#33]
Note there's an example README [here](https://github.com/UBC-MDS/dsci-522-individual-assignment-quarto-r/blob/main/README.md).

We should implement a format similar to this for M3.

In particular, we need to specify the `Rscript` commands need to be run ***inside*** the container.

**Comment by jessiezhang24** [comment]
Already updated README accordingly for milestone 3
