### ISSUE TITLE
Need to resolve Issue given by Reviewer 1

### ISSUE THREAD

**Issue by gunishakaur** [UBC-MDS/vancouver-tree-height-geo-group-33#39]
Hi all,

One of our reviewer has given the following points of the improvements: 
Link to the issue- https://github.com/UBC-MDS/data-analysis-review-2024/issues/26#issuecomment-2532688146

Improvement required :
- Maybe authors names can be added to the final report.

- Seems there're only 2 steps of data validation -- null check and distinct value check. I guess there should be 11 steps expected.

- Maybe original environment.yml and lockdown file should also be attached.

**Comment by jessiezhang24** [comment]
- The report doesn't include the name of the authors specifically but the group number. The team should state the name of each group member in the report.
   **Solved**: The authors names has been added: https://github.com/UBC-MDS/Dynamic33/commit/0b05023279301b4ecbc18b61be05a95d8b213e23
- There are very few data validation checks performed on the data. There were supposed to be 11 checks in total. The team can add a few more data validation codes.
   **Working on**: 
- There are a few typos such as Latex not rendering properly and hence the text appears in the wrong format. Additionally, in official reporting , the team could avoid using abbreviations such as a.k.a.
   **Working on**: For the typos, Replaced informal abbreviations like "a.k.a." with "also known as." 
- The team can also include a link to the Chi-squared test, incase someone wants to gain more insights on what the test does other than what has been described by the authors.
   **Solved**: Added a citation link regarding how to use Chi-squared test in R: https://github.com/UBC-MDS/Dynamic33/commit/6acb477b735dae690323e9a675e27b16bfad91b9
- The team should also state the Null and Alternative hypothesis clearly. If possible have a table on the report that shows the result of the test. This will make it easy for reader of the report to know why you came to the conclusion.
   **Solved**: Added clear hypothesis statements to our analysis, including both null and alternative hypothesis: https://github.com/UBC-MDS/Dynamic33/commit/70959bd496cf47e866d3e49b45c0fbacb5546b04. For the result part, we already included a clear statement regarding our test statistic and p-value.
- Please include the environment.yaml file and instructions of how to create the environment in the README incase a person wants to use a local environment.
   **Not applicable**: For R project, the environment.yaml file are not required
